channels:
  - conda-forge
  - defaults
dependencies:
  - openjdk
  - maven
  - make
  - cmake
  - xtensor-zarr >=0.0.8|=0.0.7=*_1
  - openimageio
  - nodejs
  - z5py >= 2.0.10
  - python == 3.7.9
  - scikit-image
  - pytest
  - zarr >= 2.8.3
  - pip
  - pandas
  - tabulate
  - pip:
      - pyn5
      - git+https://github.com/grlee77/zarrita.git@codec_update
  - r-base
  - r-remotes
  - r-stringr
  - r-httr
  - r-jsonlite
  - r-paws.storage
  - r-r.utils
  - r-curl
