---
name: Build

on: [push, pull_request]

jobs:

  get_implementations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: List implementations
        id: set-matrix
        run: echo "matrix=$(cd implementations && ls -1 | jq -ncR '[inputs]')" >> $GITHUB_OUTPUT
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  write_released:
    strategy:
      fail-fast: false
      matrix:
        implementation: ${{ fromJson(needs.get_implementations.outputs.matrix) }}
        platform: [ubuntu-latest]
        python-version: [3.8]
        zarr-python: [released]
    needs: [get_implementations]
    uses: ./.github/workflows/impl.yml
    with:
      implementation: ${{ matrix.implementation }}
      platform: ${{ matrix.platform }}
      python-version: ${{ matrix.python-version }}
      zarr-python: ${{ matrix.zarr-python }}

  # Re-run the same configurations but with a pre-release of Zarr
  write_pre:
    strategy:
      fail-fast: false
      matrix:
        implementation: ${{ fromJson(needs.get_implementations.outputs.matrix) }}
        platform: [ubuntu-latest]
        python-version: [3.8]
        zarr-python: [pre]
    needs: [get_implementations, write_released]
    uses: ./.github/workflows/impl.yml
    with:
      implementation: ${{ matrix.implementation }}
      platform: ${{ matrix.platform }}
      python-version: ${{ matrix.python-version }}
      zarr-python: ${{ matrix.zarr-python }}
